name: CI

on:
  push:  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Update Pip
      run: |
       pip install --upgrade pip
       echo "pip upgraded successfully"
       
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
